### PR TITLE
chore: improve error reporting when passing wrong values to event listeners

### PR DESCRIPTION
**Pull request by hansemannn**

### CODE REVIEW

**Comment by hansemannn** [comment]
Can someone review this? @cb1kenobi @m1ga @ewanharris

**Review by cb1kenobi — APPROVED** [review]
LGTM!

**Comment by hansemannn** [comment]
Thanks a lot! Anything I need to do regarding version bump / deployment to get this out in the wild? :)

**Comment by cb1kenobi** [comment]
@hansemannn I think we need to manually bump the version in the `package.json`, then create a new release in GitHub: https://github.com/tidev/alloy/releases/new. We can create the tag and GH should autofill the release notes based on the commits.

**Comment by cb1kenobi** [comment]
@hansemannn is the next release a minor or patch release?

**Comment by hansemannn** [comment]
A patch

**Pull request merged**
